/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mainHome;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author ivant
 */
public class InterfazHome extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public InterfazHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        miniatura1 = new javax.swing.JLabel();
        miniatura2 = new javax.swing.JLabel();
        miniatura3 = new javax.swing.JLabel();
        miniatura4 = new javax.swing.JLabel();
        miniatura5 = new javax.swing.JLabel();
        miniatura6 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        miniatura1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Miniaturas/HomeButton0.png"))); // NOI18N
        miniatura1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniatura1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miniatura1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniatura1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                miniatura1MousePressed(evt);
            }
        });
        jPanel1.add(miniatura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        miniatura2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Miniaturas/HomeButton1.png"))); // NOI18N
        miniatura2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniatura2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miniatura2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniatura2MouseExited(evt);
            }
        });
        jPanel1.add(miniatura2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, -1));

        miniatura3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Miniaturas/HomeButton2.png"))); // NOI18N
        miniatura3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniatura3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miniatura3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniatura3MouseExited(evt);
            }
        });
        jPanel1.add(miniatura3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 100, -1, -1));

        miniatura4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Miniaturas/HomeButton3.png"))); // NOI18N
        miniatura4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniatura4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miniatura4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniatura4MouseExited(evt);
            }
        });
        jPanel1.add(miniatura4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, -1, -1));

        miniatura5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Miniaturas/HomeButton4.png"))); // NOI18N
        miniatura5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniatura5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miniatura5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniatura5MouseExited(evt);
            }
        });
        jPanel1.add(miniatura5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, -1, -1));

        miniatura6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Miniaturas/HomeButton5.png"))); // NOI18N
        miniatura6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniatura6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miniatura6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniatura6MouseExited(evt);
            }
        });
        jPanel1.add(miniatura6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 470, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoBase.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-370, -200, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Utilidades n = new Utilidades();
    private void miniatura1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniatura1MouseEntered
        n.grande(miniatura1, "src/images/miniaturas/HomeButton0.png");
    }//GEN-LAST:event_miniatura1MouseEntered

    private void miniatura1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniatura1MouseExited
        n.pequenyo(miniatura1, "src/images/miniaturas/HomeButton0.png");
    }//GEN-LAST:event_miniatura1MouseExited

    private void miniatura2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniatura2MouseEntered
        n.grande(miniatura2, "src/images/miniaturas/HomeButton1.png");
    }//GEN-LAST:event_miniatura2MouseEntered

    private void miniatura2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniatura2MouseExited
        n.pequenyo(miniatura2, "src/images/miniaturas/HomeButton1.png");
    }//GEN-LAST:event_miniatura2MouseExited

    private void miniatura3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniatura3MouseEntered
        n.grande(miniatura3, "src/images/miniaturas/HomeButton2.png");
    }//GEN-LAST:event_miniatura3MouseEntered

    private void miniatura3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniatura3MouseExited
        n.pequenyo(miniatura3, "src/images/miniaturas/HomeButton2.png");
    }//GEN-LAST:event_miniatura3MouseExited

    private void miniatura4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniatura4MouseEntered
        n.grande(miniatura4, "src/images/miniaturas/HomeButton3.png");
    }//GEN-LAST:event_miniatura4MouseEntered

    private void miniatura4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniatura4MouseExited
        n.pequenyo(miniatura4, "src/images/miniaturas/HomeButton3.png");
    }//GEN-LAST:event_miniatura4MouseExited

    private void miniatura5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniatura5MouseEntered
        n.grande(miniatura5, "src/images/miniaturas/HomeButton4.png");
    }//GEN-LAST:event_miniatura5MouseEntered

    private void miniatura5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniatura5MouseExited
        n.pequenyo(miniatura5, "src/images/miniaturas/HomeButton4.png");
    }//GEN-LAST:event_miniatura5MouseExited

    private void miniatura6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniatura6MouseEntered
        n.grande(miniatura6, "src/images/miniaturas/HomeButton5.png");
    }//GEN-LAST:event_miniatura6MouseEntered

    private void miniatura6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniatura6MouseExited
        n.pequenyo(miniatura6, "src/images/miniaturas/HomeButton5.png");
    }//GEN-LAST:event_miniatura6MouseExited

    private void miniatura1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniatura1MousePressed
        InterfazGame p = new InterfazGame();
        Utilidades n = new Utilidades();
        n.showPanel(p.getFondo(), jPanel1);
        
    }//GEN-LAST:event_miniatura1MousePressed

    public JPanel getFondo() {
        return jPanel1;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazHome().setVisible(true);
            }
        });
    }

    private int cont = 1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel miniatura1;
    private javax.swing.JLabel miniatura2;
    private javax.swing.JLabel miniatura3;
    private javax.swing.JLabel miniatura4;
    private javax.swing.JLabel miniatura5;
    private javax.swing.JLabel miniatura6;
    // End of variables declaration//GEN-END:variables
}
